# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ronak Ray
tagline:          'My views on tech and life'
description:      'Hands-on QA Lead/Manager by trade, A self taught programmer. Family man of 3 heartbeats'
#url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ronak Ray'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rronakk/rronakk.github.io
